name: Physicsgun
version: 1.3
author: Calvineries
main: fr.calvineries.physicgun.Main
commands:
  physicsgun:
    description: Gives the player a physics gun.
    permission: physicsgun.give
  physgun:
    description: Gives the player a physics gun.
    permission: physicsgun.give
  physgunreload:
    description: Reload config file.*
  physicsgunreload:
    description: Reload config file.
permissions:
  physicsgun.give:
    description: Allows the player to use the physics gun command.
    default: op
  physicsgun.use:
    description: Allows the player to use the physics gun.
    default: op